---
apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: openshift-gitops-operator
spec:
  remediationAction: enforce
  severity: medium
  complianceType: musthave
  subscription:
    channel: gitops-1.16
    name: openshift-gitops-operator
    namespace: openshift-gitops-operator
    source: redhat-operators
    sourceNamespace: openshift-marketplace
  upgradeApproval: Automatic

