---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-generator
placementBindingDefaults:
  name: placementbinding-hcp-monitoring

policyDefaults:
  standards:
    - "NIST SP 800-53"
  categories:
    - "CM Configuration Management"
  controls:
    - "CM-2 Baseline Configuration"
  namespace: yantra-rhacm-policies
  consolidateManifests: false
  remediationAction: inform
  severity: medium
  generatePolicyPlacement: false



policies:
  - name: hcp-monitoring
    remediationAction: enforce
    disabled: false
    manifests:
      - path: hcp-monitoring/
        remediationAction: enforce

policySets:
- name: "hcp-monitoring"
  description: "HCP Monitoring PolicySet"
  policies:
  - hcp-monitoring
  placement:
    placementRuleName: hub-only