---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-generator
placementBindingDefaults:
  name: placementbinding-audit

policyDefaults:
  standards:
    - "NIST SP 800-53"
  categories:
    - "CM Configuration Management"
  controls:
    - "CM-2 Baseline Configuration"
  namespace: yantra-rhacm-policies
  consolidateManifests: false
  remediationAction: inform
  severity: medium

policies:
- name: audit
  remediationAction: enforce 
  disabled: false
  manifests:
    - path: audit/
      remediationAction: inform

policySets:
- name: "audit"
  description: "Auditing health checks"
  policies:
  - audit
  placement:
    placementName: all-clusters
