apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: hcp-idp-htpasswd
spec:
  remediationAction: enforce
  severity: high
  object-templates-raw: >
    {{ range $cluster := (lookup "hypershift.openshift.io/v1beta1" "HostedCluster" "" "").items }}
      {{ $cluster_name := $cluster.metadata.name }}
      {{ $namespace := $cluster.metadata.namespace }}

      # Create HostedCluster configuration
      - complianceType: musthave
        objectDefinition:
          kind: HostedCluster
          apiVersion: hypershift.openshift.io/v1beta1
          metadata:
            name: {{ $cluster_name }}
            namespace: {{ $namespace }}
          spec:
            configuration:
              oauth:
                identityProviders:
                - htpasswd:
                    fileData:
                      name: htpasswd-ocpadmin
                  mappingMethod: claim
                  name: htpasswd
                  type: HTPasswd

      # Create ExternalSecret configuration dynamically
      - complianceType: musthave
        objectDefinition:
          apiVersion: external-secrets.io/v1beta1
          kind: ExternalSecret
          metadata:
            name: gitlab-htpasswd-ocpadmin
            namespace: {{ $namespace }}  # Dynamically set namespace based on HostedCluster
          spec:
            refreshInterval: '15s'
            secretStoreRef:
              kind: ClusterSecretStore
              name: gitlab-cluster-secret-store
            target:
              name: htpasswd-ocpadmin
              creationPolicy: Owner
              template:
                data:
                  htpasswd: '{{ "{{ .htpasswd }}" }}'
            data:
              - secretKey: htpasswd
                remoteRef:
                  key: htpasswd_file
    {{ end }}
 