apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: hypershift
spec:
  template:
    spec:
      containers:
      - name: operator
        env:
        - name: METRICS_SET
          value: SRE
